# Modelos

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import os
from sklearn.model_selection import train_test_split

In [2]:
os.getcwd()

'/home/mariana/Documents/TESIS_MS/DeepLearning_Patrones_Infonavit/notebooks'

# Section 0: dataset

In [3]:
emb_pon = pd.read_pickle(r'/home/mariana/Documents/TESIS_MS/DeepLearning_Patrones_Infonavit/data/embeddings_ponderados.pkl')
emb_pon.shape

(11914, 3)

In [4]:
cols_x=['trabajador', 'vector_ponderado']
X=emb_pon[cols_x]
cols_y=['trabajador', 'cluster']
y=emb_pon[cols_y]

In [5]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.1, random_state=11)

In [6]:
X_train

trabajador                                   vector_ponderado
880      7539419  [[-0.037535205, -0.008436216, 0.022153012, -0....
7915   226311125  [[-0.016506683, 0.018259881, 0.05996791, 0.027...
5506   222624345  [[0.1800068, 0.100774996, -0.1102987, -0.00544...
7984   226354354  [[0.014875209, 0.03093428, 0.05197988, 0.00258...
6344   224429718  [[-0.041090507, -0.011688829, 0.0007811433, 0....
...          ...                                                ...
4023   221470018  [[-0.015261798, 0.07784064, -0.008496352, -0.0...
7259   224791669  [[0.0064960336, -0.006351467, 0.0001315577, 0....
5200   222311489  [[0.19620241, 0.031737555, -0.017359838, -0.01...
3775   221231504  [[-0.048305348, 0.07261606, 0.06711876, -0.029...
10137  229342651  [[-0.031530965, -0.011706721, 0.03887329, -0.0...

[10722 rows x 2 columns]

In [7]:
print(X_train.shape)
print(y_train.shape)
print(X_test.shape)
print(y_test.shape)

(10722, 2)
(10722, 2)
(1192, 2)
(1192, 2)


In [8]:
X_test.to_csv('/home/mariana/Documents/TESIS_MS/DeepLearning_Patrones_Infonavit/data/df_test_pond.csv')  

In [8]:
X_test

trabajador                                   vector_ponderado
8428   226730087  [[0.009989219, -0.017696738, 0.016274152, 0.00...
11661  230415427  [[0.02171662, -0.022568546, -0.01570976, -0.02...
4001   221452603  [[-0.11690142, -0.009922943, -0.028768778, 0.0...
2904    69261105  [[0.077872515, 0.053891666, -0.24415869, -0.09...
11722  230422998  [[-0.016170425, -0.003847118, 0.009104313, 0.0...
...          ...                                                ...
2630    69156412  [[-0.05085626, 0.043203, 0.05229876, 0.0107666...
10155  229370411  [[0.009077634, 0.039996695, 0.06657322, 0.0058...
3887   221328405  [[0.064717524, 0.01880022, 0.05265964, -0.0068...
6670   224602874  [[-0.029570578, -0.0012330536, 0.011599244, 0....
6065   224267593  [[0.09576804, 0.0695832, 0.08887367, 1.1427328...

[1192 rows x 2 columns]

In [9]:
emb_preg= pd.read_pickle(r'/home/mariana/Documents/TESIS_MS/DeepLearning_Patrones_Infonavit/data/embeddings_pregunta.pkl')
emb_preg.shape

(214452, 3)

In [10]:
cols_x=['trabajador', 'rows']
X1=emb_preg[cols_x]
cols_y=['trabajador', 'cluster']
y1=emb_preg[cols_y]

In [11]:
X1_train, X1_test, y1_train, y1_test = train_test_split(X1, y1, test_size=0.1, random_state=11)

In [12]:
X1_test

trabajador                                               rows
25707     7546547  [[0.013036218471825123, -0.005430428311228752,...
78814   221605168  [[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,...
83411   221793641  [[0.2145978957414627, 0.29017874598503113, -0....
192815  229984493  [[0.2145978957414627, 0.29017874598503113, -0....
19851     7542603  [[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,...
...           ...                                                ...
168292  227297052  [[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,...
185721  229586241  [[0.16104117035865784, 0.24619978666305542, 0....
204291  230218664  [[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,...
34349    68588226  [[-0.04584771767258644, 0.015893828123807907, ...
92194   222262271  [[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,...

[21446 rows x 2 columns]

In [13]:
print(X1_train.shape)
print(y1_train.shape)
print(X1_test.shape)
print(y1_test.shape)

(193006, 2)
(193006, 2)
(21446, 2)
(21446, 2)


In [14]:
X1_test.to_csv('/home/mariana/Documents/TESIS_MS/DeepLearning_Patrones_Infonavit/data/df_test_preg.csv')  

In [16]:
emb_preg.cluster.unique()

<StringArray>
['3', '6', '7', '0', '1', '2', '4', '5']
Length: 8, dtype: string

# Section 1: MLP - fully connected

In [14]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Input, Dense, Dropout
from tensorflow.keras.regularizers import l2

In [148]:
# Put input data into vector format for training MLP
X = np.array(X_train['vector_ponderado'].to_list())
print(X.shape)

X = X.reshape((len(X), -1))
print(X.shape)

(10722, 30, 128)
(10722, 3840)


In [149]:
np.any(np.isnan(X))

True

In [150]:
X=np.nan_to_num(X)

In [151]:
np.any(np.isnan(X))

False

In [134]:
# Put output data into vector format for training MLP
y = y_train['cluster'].to_numpy()
print(y)

y = tf.one_hot(y, depth=8)
print(y)

['3' '3' '1' ... '7' '7' '3']
tf.Tensor(
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 0.]], shape=(10722, 8), dtype=float32)


In [135]:
# Put input data into vector format for training MLP
X1 = np.array(X1_train['rows'].to_list())
print(X1.shape)

X1= X1.reshape((len(X1), -1))
print(X1.shape)

(193006, 30, 128)
(193006, 3840)


In [136]:
np.any(np.isnan(X1))

False

In [137]:
# Put output data into vector format for training MLP
y1 = y1_train['cluster'].to_numpy()
print(y1)

y1 = tf.one_hot(y1, depth=8)
print(y1)

['3' '3' '7' ... '6' '4' '3']
tf.Tensor(
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 1.]
 ...
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]], shape=(193006, 8), dtype=float32)


In [138]:
# Creat MLP
mlp = Sequential([
                  Input(shape=(X.shape[1])),
                  Dense(512, activation='relu'),
                  Dropout(0.5),
                  Dense(512, activation='relu',activity_regularizer=l2(0.5)),
                  Dense(128, activation='relu'),
                  Dense( 32, activation='relu'),
                  Dense(y.shape[1], activation='softmax')
])

mlp.summary()

Model: "sequential_18"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_63 (Dense)             (None, 512)               1966592   
_________________________________________________________________
dropout_14 (Dropout)         (None, 512)               0         
_________________________________________________________________
dense_64 (Dense)             (None, 512)               262656    
_________________________________________________________________
dense_65 (Dense)             (None, 128)               65664     
_________________________________________________________________
dense_66 (Dense)             (None, 32)                4128      
_________________________________________________________________
dense_67 (Dense)             (None, 8)                 264       
Total params: 2,299,304
Trainable params: 2,299,304
Non-trainable params: 0
___________________________________________

In [189]:
# Creat MLP
mlp = Sequential([
                  Input(shape=(X.shape[1])),
                  Dense(512, activation='relu'),
                  Dropout(0.5),
                  Dense(128, activation='relu'),
                  Dense( 32, activation='relu'),
                  Dense(y.shape[1], activation='softmax')
])

mlp.summary()

Model: "sequential_23"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_88 (Dense)             (None, 512)               1966592   
_________________________________________________________________
dropout_17 (Dropout)         (None, 512)               0         
_________________________________________________________________
dense_89 (Dense)             (None, 128)               65664     
_________________________________________________________________
dense_90 (Dense)             (None, 32)                4128      
_________________________________________________________________
dense_91 (Dense)             (None, 8)                 264       
Total params: 2,036,648
Trainable params: 2,036,648
Non-trainable params: 0
_________________________________________________________________


In [203]:
# Creat MLP
mlp1 = Sequential([
                  Input(shape=(X1.shape[1])),
                  Dense(512, activation='relu'),
                  Dropout(0.5),
                  Dense(128, activation='relu'),
                  Dense( 32, activation='relu'),
                  Dense(y1.shape[1], activation='softmax')
])

mlp1.summary()

Model: "sequential_24"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_92 (Dense)             (None, 512)               1966592   
_________________________________________________________________
dropout_18 (Dropout)         (None, 512)               0         
_________________________________________________________________
dense_93 (Dense)             (None, 128)               65664     
_________________________________________________________________
dense_94 (Dense)             (None, 32)                4128      
_________________________________________________________________
dense_95 (Dense)             (None, 8)                 264       
Total params: 2,036,648
Trainable params: 2,036,648
Non-trainable params: 0
_________________________________________________________________


In [159]:
# Creat MLP
mlp1 = Sequential([
                  Input(shape=(X1.shape[1])),
                  Dense(512, activation='relu'),
                  Dropout(0.5),
                  Dense(512, activation='relu',activity_regularizer=l2(0.5)),
                  Dense(128, activation='relu'),
                  Dense( 32, activation='relu'),
                  Dense(y1.shape[1], activation='softmax')
])

mlp1.summary()

Model: "sequential_20"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_73 (Dense)             (None, 512)               1966592   
_________________________________________________________________
dropout_16 (Dropout)         (None, 512)               0         
_________________________________________________________________
dense_74 (Dense)             (None, 512)               262656    
_________________________________________________________________
dense_75 (Dense)             (None, 128)               65664     
_________________________________________________________________
dense_76 (Dense)             (None, 32)                4128      
_________________________________________________________________
dense_77 (Dense)             (None, 8)                 264       
Total params: 2,299,304
Trainable params: 2,299,304
Non-trainable params: 0
___________________________________________

In [190]:
# Define training parameters
mlp.compile(optimizer='adam', loss='categorical_crossentropy', metrics='categorical_accuracy')

In [204]:
# Define training parameters
mlp1.compile(optimizer='adam', loss='categorical_crossentropy', metrics='categorical_accuracy')

In [191]:
mlp.fit(x=X, y=y, batch_size=32, epochs=100, validation_split=0.1)

Epoch 1/100
302/302 [==============================] - 2s 6ms/step - loss: 1.5652 - categorical_accuracy: 0.3970 - val_loss: 1.3846 - val_categorical_accuracy: 0.4604
Epoch 2/100
302/302 [==============================] - 2s 5ms/step - loss: 1.4029 - categorical_accuracy: 0.4517 - val_loss: 1.3824 - val_categorical_accuracy: 0.4529
Epoch 3/100
302/302 [==============================] - 2s 5ms/step - loss: 1.3934 - categorical_accuracy: 0.4570 - val_loss: 1.3658 - val_categorical_accuracy: 0.4762
Epoch 4/100
302/302 [==============================] - 2s 5ms/step - loss: 1.3735 - categorical_accuracy: 0.4695 - val_loss: 1.3578 - val_categorical_accuracy: 0.4678
Epoch 5/100
302/302 [==============================] - 2s 5ms/step - loss: 1.3399 - categorical_accuracy: 0.4821 - val_loss: 1.3829 - val_categorical_accuracy: 0.4539
Epoch 6/100
302/302 [==============================] - 2s 5ms/step - loss: 1.3461 - categorical_accuracy: 0.4693 - val_loss: 1.3502 - val_categorical_accuracy: 0.466

Epoch 50/100
302/302 [==============================] - 2s 5ms/step - loss: 0.9605 - categorical_accuracy: 0.6240 - val_loss: 1.8841 - val_categorical_accuracy: 0.4669
Epoch 51/100
302/302 [==============================] - 2s 5ms/step - loss: 0.9402 - categorical_accuracy: 0.6271 - val_loss: 1.8906 - val_categorical_accuracy: 0.4557
Epoch 52/100
302/302 [==============================] - 2s 5ms/step - loss: 0.9532 - categorical_accuracy: 0.6253 - val_loss: 1.8332 - val_categorical_accuracy: 0.4632
Epoch 53/100
302/302 [==============================] - 2s 5ms/step - loss: 0.9488 - categorical_accuracy: 0.6377 - val_loss: 1.9180 - val_categorical_accuracy: 0.4613
Epoch 54/100
302/302 [==============================] - 2s 5ms/step - loss: 0.9438 - categorical_accuracy: 0.6353 - val_loss: 1.8661 - val_categorical_accuracy: 0.4511
Epoch 55/100
302/302 [==============================] - 2s 5ms/step - loss: 0.9509 - categorical_accuracy: 0.6319 - val_loss: 1.8821 - val_categorical_accuracy:

Epoch 99/100
302/302 [==============================] - 2s 5ms/step - loss: 0.8077 - categorical_accuracy: 0.6837 - val_loss: 2.0619 - val_categorical_accuracy: 0.4623
Epoch 100/100
302/302 [==============================] - 2s 5ms/step - loss: 0.8571 - categorical_accuracy: 0.6683 - val_loss: 2.1975 - val_categorical_accuracy: 0.4716


In [ ]:
mlp1.fit(x=X1, y=y1, batch_size=32, epochs=100, validation_split=0.1)

### Prediction

In [192]:
x_test= np.array(X_test['vector_ponderado'].to_list())
print(x_test.shape)

x_test= x_test.reshape((len(x_test), -1))
print(x_test.shape)

(1192, 30, 128)
(1192, 3840)


In [193]:
np.any(np.isnan(x_test))

True

In [194]:
x_test=np.nan_to_num(x_test)

In [195]:
np.any(np.isnan(x_test))

False

In [196]:
# Put output data into vector format for training MLP
Y_test = y_test['cluster'].to_numpy()
print(Y_test)

Y_test = tf.one_hot(Y_test, depth=8)
print(Y_test)

['1' '3' '1' ... '1' '6' '3']
tf.Tensor(
[[0. 1. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 ...
 [0. 1. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 0. 0.]], shape=(1192, 8), dtype=float32)


In [197]:
# Put input data into vector format for training MLP
x1_test = np.array(X1_test['rows'].to_list())
print(x1_test.shape)

x1_test= x1_test.reshape((len(x1_test), -1))
print(x1_test.shape)

(21446, 30, 128)
(21446, 3840)


In [198]:
np.any(np.isnan(x1_test))

False

In [199]:
# Put output data into vector format for training MLP
Y1_test= y1_test['cluster'].to_numpy()
print(Y1_test)

Y1_test= tf.one_hot(Y1_test, depth=8)
print(Y1_test)

['3' '3' '3' ... '6' '4' '3']
tf.Tensor(
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]], shape=(21446, 8), dtype=float32)


In [200]:
mlp.evaluate(X, y)

336/336 [==============================] - 0s 1ms/step - loss: 0.8260 - categorical_accuracy: 0.7115


[0.8260345458984375, 0.7115277051925659]

In [201]:
mlp.evaluate(x_test, Y_test)

38/38 [==============================] - 0s 1ms/step - loss: 2.3160 - categorical_accuracy: 0.4555


[2.316042423248291, 0.4555369019508362]

In [187]:
mlp1.evaluate(X1, y1)

6032/6032 [==============================] - 8s 1ms/step - loss: 1.4924 - categorical_accuracy: 0.4417


[1.4923914670944214, 0.44173237681388855]

In [188]:
mlp1.evaluate(x1_test, Y1_test)

671/671 [==============================] - 1s 1ms/step - loss: 2.1487 - categorical_accuracy: 0.4093


[2.1487486362457275, 0.40926048159599304]

In [57]:
p=mlp.predict(X)
p_1=mlp1.predict(X1)

In [58]:
y_classes=p.argmax(axis=-1)

In [59]:
y1_classes=p_1.argmax(axis=-1)

In [61]:
print(y_classes)
print(y1_classes)

[0 3 0 ... 0 7 0]
[0 0 5 ... 0 0 0]


# Section 2: Conv1D NN

In [206]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Input, Dense, Conv1D, MaxPool1D, Flatten

In [207]:
# Put input data into vector format for training MLP
X = np.array(X_train['vector_ponderado'].to_list())
print(X.shape)

(10722, 30, 128)


In [208]:
np.any(np.isnan(X))

True

In [209]:
X=np.nan_to_num(X)

In [210]:
np.any(np.isnan(X))

False

In [211]:
# Put output data into vector format for training MLP
y= y_train['cluster'].to_numpy()
print(y)

y= tf.one_hot(y, depth=8)
print(y)

['3' '3' '1' ... '7' '7' '3']
tf.Tensor(
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 0.]], shape=(10722, 8), dtype=float32)


In [212]:
# Put input data into vector format for training MLP
X1 = np.array(X1_train['rows'].to_list())
print(X1.shape)

(193006, 30, 128)


In [21]:
# Put output data into vector format for training MLP
y1 = y1_train['cluster'].to_numpy()
print(y1)

y1 = tf.one_hot(y1, depth=8)
print(y1)

['3' '3' '7' ... '6' '4' '3']
tf.Tensor(
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 1.]
 ...
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]], shape=(193006, 8), dtype=float32)


In [233]:
# Creat MLP
cnn = Sequential()
cnn.add(Input(shape=(X.shape[1], X.shape[2])))
cnn.add(Conv1D(64, 3, padding='same', activation='relu'))
cnn.add(MaxPool1D())
cnn.add(Dropout(.5))
cnn.add(Conv1D(128, 3, padding='same', activation='relu'))
cnn.add(MaxPool1D())
cnn.add(Conv1D(256, 3, padding='same', activation='relu'))
cnn.add(MaxPool1D())
cnn.add(Conv1D(512, 3, padding='same', activation='relu'))
cnn.add(MaxPool1D())
cnn.add(Flatten())
cnn.add(Dense(32, activation='relu', activity_regularizer=l2(.5)))
cnn.add(Dense(64, activation='relu'))
cnn.add(Dense(y.shape[1], activation='softmax'))
cnn.summary()

Model: "sequential_28"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv1d_52 (Conv1D)           (None, 30, 64)            24640     
_________________________________________________________________
max_pooling1d_52 (MaxPooling (None, 15, 64)            0         
_________________________________________________________________
dropout_21 (Dropout)         (None, 15, 64)            0         
_________________________________________________________________
conv1d_53 (Conv1D)           (None, 15, 128)           24704     
_________________________________________________________________
max_pooling1d_53 (MaxPooling (None, 7, 128)            0         
_________________________________________________________________
conv1d_54 (Conv1D)           (None, 7, 256)            98560     
_________________________________________________________________
max_pooling1d_54 (MaxPooling (None, 3, 256)          

In [115]:
# Creat MLP
cnn = Sequential()
cnn.add(Input(shape=(X1.shape[1], X1.shape[2])))
cnn.add(Conv1D(64, 3, padding='same', activation='relu'))
cnn.add(MaxPool1D())
cnn.add(Dropout(.5))
cnn.add(Conv1D(128, 3, padding='same', activation='relu'))
cnn.add(MaxPool1D())
cnn.add(Conv1D(256, 3, padding='same', activation='relu'))
cnn.add(MaxPool1D())
cnn.add(Conv1D(512, 3, padding='same', activation='relu'))
cnn.add(MaxPool1D())
cnn.add(Flatten())
cnn.add(Dense(32, activation='relu',activity_regularizer=l2(0.5)))
cnn.add(Dense(y1.shape[1], activation='softmax'))
cnn.summary()

Model: "sequential_13"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv1d_20 (Conv1D)           (None, 30, 64)            24640     
_________________________________________________________________
max_pooling1d_20 (MaxPooling (None, 15, 64)            0         
_________________________________________________________________
dropout_11 (Dropout)         (None, 15, 64)            0         
_________________________________________________________________
conv1d_21 (Conv1D)           (None, 15, 128)           24704     
_________________________________________________________________
max_pooling1d_21 (MaxPooling (None, 7, 128)            0         
_________________________________________________________________
conv1d_22 (Conv1D)           (None, 7, 256)            98560     
_________________________________________________________________
max_pooling1d_22 (MaxPooling (None, 3, 256)          

In [127]:
# Creat MLP
cnn = Sequential()
cnn.add(Input(shape=(X1.shape[1], X1.shape[2])))
cnn.add(Conv1D(64, 3, padding='same', activation='relu'))
cnn.add(MaxPool1D())
cnn.add(Conv1D(128, 3, padding='same', activation='relu'))
cnn.add(MaxPool1D())
cnn.add(Conv1D(256, 3, padding='same', activation='relu'))
cnn.add(MaxPool1D())
cnn.add(Conv1D(512, 3, padding='same', activation='relu'))
cnn.add(MaxPool1D())
cnn.add(Flatten())
cnn.add(Dense(32, activation='relu'))
cnn.add(Dense(y1.shape[1], activation='softmax'))
cnn.summary()

Model: "sequential_17"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv1d_36 (Conv1D)           (None, 30, 64)            24640     
_________________________________________________________________
max_pooling1d_36 (MaxPooling (None, 15, 64)            0         
_________________________________________________________________
conv1d_37 (Conv1D)           (None, 15, 128)           24704     
_________________________________________________________________
max_pooling1d_37 (MaxPooling (None, 7, 128)            0         
_________________________________________________________________
conv1d_38 (Conv1D)           (None, 7, 256)            98560     
_________________________________________________________________
max_pooling1d_38 (MaxPooling (None, 3, 256)            0         
_________________________________________________________________
conv1d_39 (Conv1D)           (None, 3, 512)          

In [228]:
# Creat MLP
cnn = Sequential()
cnn.add(Input(shape=(X.shape[1], X.shape[2])))
cnn.add(Conv1D(64, 3, padding='same', activation='relu'))
cnn.add(MaxPool1D())
cnn.add(Dropout(.5))
cnn.add(Conv1D(128, 3, padding='same', activation='relu'))
cnn.add(MaxPool1D())
cnn.add(Conv1D(256, 3, padding='same', activation='relu'))
cnn.add(MaxPool1D())
cnn.add(Conv1D(512, 3, padding='same', activation='relu'))
cnn.add(MaxPool1D())
cnn.add(Flatten())
cnn.add(Dense(32, activation='relu'))
cnn.add(Dense(y.shape[1], activation='softmax'))
cnn.summary()

Model: "sequential_27"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv1d_48 (Conv1D)           (None, 30, 64)            24640     
_________________________________________________________________
max_pooling1d_48 (MaxPooling (None, 15, 64)            0         
_________________________________________________________________
dropout_20 (Dropout)         (None, 15, 64)            0         
_________________________________________________________________
conv1d_49 (Conv1D)           (None, 15, 128)           24704     
_________________________________________________________________
max_pooling1d_49 (MaxPooling (None, 7, 128)            0         
_________________________________________________________________
conv1d_50 (Conv1D)           (None, 7, 256)            98560     
_________________________________________________________________
max_pooling1d_50 (MaxPooling (None, 3, 256)          

In [234]:
# Define training parameters
cnn.compile(optimizer='adam', loss='categorical_crossentropy',metrics='categorical_accuracy')

In [52]:
cnn.fit(x=X1, y=y1, batch_size=32, epochs=100, validation_split=0.1)

Epoch 1/100
5429/5429 [==============================] - 29s 5ms/step - loss: 1.6422 - categorical_accuracy: 0.4105 - val_loss: 1.5091 - val_categorical_accuracy: 0.4146
Epoch 2/100
5429/5429 [==============================] - 28s 5ms/step - loss: 1.5123 - categorical_accuracy: 0.4117 - val_loss: 1.5032 - val_categorical_accuracy: 0.4147
Epoch 3/100
5429/5429 [==============================] - 27s 5ms/step - loss: 1.5069 - categorical_accuracy: 0.4140 - val_loss: 1.5011 - val_categorical_accuracy: 0.4152
Epoch 4/100
5429/5429 [==============================] - 27s 5ms/step - loss: 1.5024 - categorical_accuracy: 0.4150 - val_loss: 1.5053 - val_categorical_accuracy: 0.4146
Epoch 5/100
5429/5429 [==============================] - 27s 5ms/step - loss: 1.5022 - categorical_accuracy: 0.4156 - val_loss: 1.4993 - val_categorical_accuracy: 0.4150
Epoch 6/100
5429/5429 [==============================] - 27s 5ms/step - loss: 1.5028 - categorical_accuracy: 0.4147 - val_loss: 1.4991 - val_categoric

Epoch 49/100
5429/5429 [==============================] - 27s 5ms/step - loss: 1.4987 - categorical_accuracy: 0.4154 - val_loss: 1.4961 - val_categorical_accuracy: 0.4168
Epoch 50/100
5429/5429 [==============================] - 27s 5ms/step - loss: 1.4980 - categorical_accuracy: 0.4147 - val_loss: 1.4993 - val_categorical_accuracy: 0.4155
Epoch 51/100
5429/5429 [==============================] - 27s 5ms/step - loss: 1.4986 - categorical_accuracy: 0.4146 - val_loss: 1.4974 - val_categorical_accuracy: 0.4160
Epoch 52/100
5429/5429 [==============================] - 27s 5ms/step - loss: 1.4987 - categorical_accuracy: 0.4163 - val_loss: 1.4966 - val_categorical_accuracy: 0.4161
Epoch 53/100
5429/5429 [==============================] - 27s 5ms/step - loss: 1.5002 - categorical_accuracy: 0.4156 - val_loss: 1.4973 - val_categorical_accuracy: 0.4164
Epoch 54/100
5429/5429 [==============================] - 27s 5ms/step - loss: 1.4996 - categorical_accuracy: 0.4138 - val_loss: 1.4971 - val_cat

Epoch 97/100
5429/5429 [==============================] - 27s 5ms/step - loss: 1.4994 - categorical_accuracy: 0.4147 - val_loss: 1.4974 - val_categorical_accuracy: 0.4151
Epoch 98/100
5429/5429 [==============================] - 27s 5ms/step - loss: 1.5000 - categorical_accuracy: 0.4146 - val_loss: 1.4977 - val_categorical_accuracy: 0.4157
Epoch 99/100
5429/5429 [==============================] - 27s 5ms/step - loss: 1.4971 - categorical_accuracy: 0.4158 - val_loss: 1.4974 - val_categorical_accuracy: 0.4142
Epoch 100/100
5429/5429 [==============================] - 27s 5ms/step - loss: 1.4960 - categorical_accuracy: 0.4154 - val_loss: 1.4973 - val_categorical_accuracy: 0.4157


In [235]:
cnn.fit(x=X, y=y, batch_size=32, epochs=100, validation_split=0.1)

Epoch 1/100
302/302 [==============================] - 2s 6ms/step - loss: 1.7958 - categorical_accuracy: 0.4010 - val_loss: 1.4518 - val_categorical_accuracy: 0.4604
Epoch 2/100
302/302 [==============================] - 2s 5ms/step - loss: 1.4730 - categorical_accuracy: 0.4386 - val_loss: 1.4048 - val_categorical_accuracy: 0.4706
Epoch 3/100
302/302 [==============================] - 2s 5ms/step - loss: 1.4116 - categorical_accuracy: 0.4578 - val_loss: 1.3699 - val_categorical_accuracy: 0.4809
Epoch 4/100
302/302 [==============================] - 2s 5ms/step - loss: 1.3956 - categorical_accuracy: 0.4575 - val_loss: 1.3692 - val_categorical_accuracy: 0.4697
Epoch 5/100
302/302 [==============================] - 2s 5ms/step - loss: 1.3867 - categorical_accuracy: 0.4690 - val_loss: 1.3602 - val_categorical_accuracy: 0.4725
Epoch 6/100
302/302 [==============================] - 2s 5ms/step - loss: 1.3691 - categorical_accuracy: 0.4662 - val_loss: 1.3564 - val_categorical_accuracy: 0.484

Epoch 50/100
302/302 [==============================] - 2s 5ms/step - loss: 1.1998 - categorical_accuracy: 0.5405 - val_loss: 1.3839 - val_categorical_accuracy: 0.4688
Epoch 51/100
302/302 [==============================] - 2s 5ms/step - loss: 1.1979 - categorical_accuracy: 0.5449 - val_loss: 1.3959 - val_categorical_accuracy: 0.4632
Epoch 52/100
302/302 [==============================] - 2s 5ms/step - loss: 1.2119 - categorical_accuracy: 0.5325 - val_loss: 1.4007 - val_categorical_accuracy: 0.4678
Epoch 53/100
302/302 [==============================] - 2s 5ms/step - loss: 1.2128 - categorical_accuracy: 0.5373 - val_loss: 1.3830 - val_categorical_accuracy: 0.4809
Epoch 54/100
302/302 [==============================] - 2s 5ms/step - loss: 1.2142 - categorical_accuracy: 0.5287 - val_loss: 1.3914 - val_categorical_accuracy: 0.4809
Epoch 55/100
302/302 [==============================] - 2s 5ms/step - loss: 1.2154 - categorical_accuracy: 0.5365 - val_loss: 1.3968 - val_categorical_accuracy:

Epoch 99/100
302/302 [==============================] - 2s 5ms/step - loss: 1.1326 - categorical_accuracy: 0.5640 - val_loss: 1.4896 - val_categorical_accuracy: 0.4604
Epoch 100/100
302/302 [==============================] - 2s 5ms/step - loss: 1.1222 - categorical_accuracy: 0.5695 - val_loss: 1.4678 - val_categorical_accuracy: 0.4613


### Prediction

In [236]:
# Put input data into vector format for training MLP
x_test = np.array(X_test['vector_ponderado'].to_list())
print(x_test.shape)

(1192, 30, 128)


In [237]:
np.any(np.isnan(x_test))

True

In [238]:
x_test=np.nan_to_num(x_test)

In [239]:
np.any(np.isnan(x_test))

False

In [240]:
# Put output data into vector format for training MLP
Y_test= y_test['cluster'].to_numpy()
print(Y_test)

Y_test= tf.one_hot(Y_test, depth=8)
print(Y_test)

['1' '3' '1' ... '1' '6' '3']
tf.Tensor(
[[0. 1. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 ...
 [0. 1. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 0. 0.]], shape=(1192, 8), dtype=float32)


In [97]:
# Put input data into vector format for training MLP
X1 = np.array(X1_test['rows'].to_list())
print(X1.shape)

(21446, 30, 128)


In [98]:
# Put output data into vector format for training MLP
y1 = y1_test['cluster'].to_numpy()
print(y1)

y1 = tf.one_hot(y1, depth=8)
print(y1)

['3' '3' '3' ... '6' '4' '3']
tf.Tensor(
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]], shape=(21446, 8), dtype=float32)


In [241]:
p2=cnn.evaluate(X,y)

336/336 [==============================] - 0s 1ms/step - loss: 1.0337 - categorical_accuracy: 0.6247


In [242]:
p2=cnn.evaluate(x_test,Y_test)

38/38 [==============================] - 0s 2ms/step - loss: 1.4970 - categorical_accuracy: 0.4505


In [129]:
p3=cnn.evaluate(X1,y1)

671/671 [==============================] - 1s 1ms/step - loss: 2.0802 - categorical_accuracy: 0.0158
